#!/usr/bin/env python
# coding: utf-8

# In[ ]:





# In[6]:


#case study: card shuffling and dealing Problem
from dataclasses import dataclass
from typing import ClassVar, List
import random

@dataclass
class Card:
    """Card data class with class attributes, data attributes,
    autogenerated methods and explicitly defined methods."""
    
    FACES: ClassVar[List[str]] = ['Ace', '2', '3', '4', '5', '6', '7',
                                  '8', '9', '10', 'Jack', 'Queen', 'King']
    SUITS: ClassVar[List[str]] = ['Hearts', 'Diamonds', 'Clubs', 'Spades']
    
    face: str
    suit: str
    
    @property
    def image_name(self):
        """Return the Card's image file name."""
        return str(self).replace(' ', '_') + '.png'
    
    def __str__(self):
        """Return string representation for str()."""
        return f'{self.face} of {self.suit}'
    
    def __format__(self, format_spec):
        """Return formatted string representation."""
        return f'{str(self):{format_spec}}'

class DeckOfCards:
    """Deck of playing cards."""
    def __init__(self):
        """Create deck of 52 Card objects."""
        self._cards = [Card(face, suit) for suit in Card.SUITS for face in Card.FACES]
    
    def __str__(self):
        """Return string representation of the deck."""
        return ' '.join(f'{card:19}' for card in self._cards)
    
    def shuffle(self):
        """Shuffle deck of cards."""
        random.shuffle(self._cards)
    
    def deal_card(self):
        """Deal one card from the deck."""
        return self._cards.pop() if self._cards else None

# Example Usage
if __name__ == "__main__":
    # Create a card
    c1 = Card(Card.FACES[0], Card.SUITS[3])
    print(c1)  # Ace of Spades
    print(c1.image_name)  # Ace_of_Spades.png
    
    # Create a deck
    deck = DeckOfCards()
    print(deck)  # Print all cards in order
    
    # Shuffle deck
    deck.shuffle()
    print(deck)  # Print shuffled deck
    
    # Deal a card
    dealt_card = deck.deal_card()
    print(f'Dealt card: {dealt_card}')


# In[ ]:




